services:
  - type: web
    name: mern-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: MONGODB_URI
        value: your-mongodb-connection-uri-here
      - key: NODE_ENV
        value: production
